### ISSUE TITLE
Error when sending empty messages / zlib error inflate -3: "invalid stored block lengths"

### ISSUE THREAD

**Issue by bsergean** [machinezone/IXWebSocket#167]
This breaks the python websockets library.

```
Error in data transfer
Traceback (most recent call last):
  File "/Users/bsergeant/src/foss/cobra/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/Users/bsergeant/src/foss/cobra/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/bsergeant/src/foss/cobra/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/bsergeant/src/foss/cobra/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/Users/bsergeant/src/foss/cobra/venv/lib/python3.8/site-packages/websockets/framing.py", line 142, in read
    frame = extension.decode(frame, max_size=max_size)
  File "/Users/bsergeant/src/foss/cobra/venv/lib/python3.8/site-packages/websockets/extensions/permessage_deflate.py", line 129, in decode
    data = self.decoder.decompress(data, max_length)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
```

And also while running against the libwebsockets test server.

```
build$ ./bin/libwebsockets-test-server                                             
[2020/03/23 14:51:21:2373] N: libwebsockets test server - license MIT
[2020/03/23 14:51:21:2379] N: (C) Copyright 2010-2018 Andy Green <andy@warmcat.com>
Using resource path "/usr/local/share/libwebsockets-test-server"
[2020/03/23 14:51:26:4079] E: lws_extension_callback_pm_deflate: zlib error inflate -3: "invalid stored block lengths"
```

(built with `cmake -DLWS_WITH_MBEDTLS=1 -DLWS_WITH_ZLIB=1 -DLWS_WITHOUT_EXTENSIONS=OFF ..`)

The problem is here I think, can't remember why I'm doing this:

```
        if (in.empty())
        {
            uint8_t buf[6] = {0x02, 0x00, 0x00, 0x00, 0xff, 0xff};
            out.append((char*) (buf), 6);
            return true;
        }
```

**Comment by bsergean** [comment]
This is from the websocketpp code base.

```
        if (in.empty()) {
            uint8_t buf[6] = {0x02, 0x00, 0x00, 0x00, 0xff, 0xff};
            out.append((char *)(buf),6);
            return lib::error_code();
        }
```
