### ISSUE TITLE
TLS chunking on Windows/mbedTLS crashes server

### ISSUE THREAD

**Issue by luastoned** [machinezone/IXWebSocket#323]
Hello, I've read through #140 and I am experiencing sort of similar issues here.

Anything below 50ms sleep in the progress callback causes my very simple ws server to crash.

The server is running Node v16 and is proxied through nginx  to be secure / available via wss.
The client ran versions v10.4.0, v11.0.8 and v11.3.1 with both mbedTLS v2 and mbedTLS v3.

The server code:
```
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8080, perMessageDeflate: false });

wss.on('connection', (ws) => {
  ws.on('message', (data) => {
    console.log('received', data.length);
  });
});
```

The simplified client code:
```
std::string generateRandomData(size_t length = 0) {
	static const std::string allowed_chars{ "123456789BCDFGHJKLMNPQRSTVWXZbcdfghjklmnpqrstvwxz" };

	static thread_local std::default_random_engine randomEngine(std::random_device{}());
	static thread_local std::uniform_int_distribution<int> randomDistribution(0, allowed_chars.size() - 1);

	std::string id(length ? length : 32, '\0');
	for (std::string::value_type& c : id) {
		c = allowed_chars[randomDistribution(randomEngine)];
	}

	return id;
}

void messageCallback(const ix::WebSocketMessagePtr &msg)
{
	if (msg->type == ix::WebSocketMessageType::Message) {
		std::cout << "> message: " << msg->str << std::endl;
	}

	if (msg->type == ix::WebSocketMessageType::Open) {
		std::cout << "> connected" << std::endl;
	}

	if (msg->type == ix::WebSocketMessageType::Close) {
		std::cout << "> disconnected " << msg->closeInfo.code << ", " << msg->closeInfo.reason << std::endl;
	}

	if (msg->type == ix::WebSocketMessageType::Error) {
		std::cout << "> error " << msg->errorInfo.http_status << ": " << msg->errorInfo.reason << std::endl;
	}
}

bool progressCallback(int32_t current, int32_t total) {
	printf("progress: %d/%d\n", current + 1, total);
	std::this_thread::sleep_for(std::chrono::milliseconds(25));
	return true;
}

int main(void) {
	std::string url("wss://ixws.luastoned.com");
	std::string data = generateRandomData(2 * 1000 * 1000);

	ix::initNetSystem();

	webSocket.setUrl(url);
	webSocket.disablePerMessageDeflate();
	webSocket.setOnMessageCallback(messageCallback);

	std::cout << "> connecting to " << url << " ..." << std::endl;
	webSocket.start();

	std::cout << "> sending data" << std::endl;
	webSocket.send(data, true, progressCallback);

	// Stop the connection
	webSocket.stop();
	ix::uninitNetSystem();

	return 0;
}
```

Upon execution I get the following:

```
> connecting to wss://ixws.luastoned.com ...
> connected
> sending data
progress: 1/61
progress: 2/61
progress: 3/61
> disconnected 1002,
> disconnected 1002,
> error 502: Expecting status 101 (Switching Protocol), got 502 status connecting to wss://ixws.luastoned.com, HTTP Status line: HTTP/1.1 502 Bad Gateway
```
and
```
RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (ixws-debug/node_modules/ws/lib/receiver.js:176:14)
    at Receiver.startLoop (ixws-debug/node_modules/ws/lib/receiver.js:136:22)
    at Receiver._write (ixws-debug/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (ixws-debug/node_modules/ws/lib/websocket.js:1116:35)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (ixws-debug/node_modules/ws/lib/websocket.js:1002:13)
    at Receiver.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_UNEXPECTED_RSV_2_3',
  [Symbol(status-code)]: 1002
}
```

**Comment by luastoned** [comment]
It crashes the most basic python server as well. (taken from ws/broadcast-server.py)

```
connection handler failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/framing.py", line 80, in read
    opcode = frames.Opcode(head1 & 0b00001111)
  File "/usr/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 663, in __new__
    raise ve_exc
ValueError: 11 is not a valid Opcode

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 1068, in read_message
    frame = await self.read_data_frame(max_size=max_size)
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 1144, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/framing.py", line 82, in read
    raise ProtocolError("invalid opcode") from exc
websockets.exceptions.ProtocolError: invalid opcode

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "server.py", line 13, in echo
    async for message in websocket:
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 481, in __aiter__
    yield await self.recv()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1002 (protocol error); no close frame received
```

**Comment by bsergean** [comment]
Maybe there was a big regression ... odd.

I just started using caddy-server which is like nginx to handle TLS. Is your service available on the wide internet ? Can you reproduce the problem with the ws command line tool, which is bundled with this project ?

What version of mbedtls are you using ? We have an internal project that is using mbedtls and that can talk fine to a python server (cobra) over ssl (with nginx too I believe).

**Comment by bsergean** [comment]
```
ALHttp-Cpp$ ws connect wss://ixws.luastoned.com
Type Ctrl-D to exit prompt...
Connecting to url: wss://ixws.luastoned.com
> Connection error: Expecting status 101 (Switching Protocol), got 502 status connecting to wss://ixws.luastoned.com, HTTP Status line: HTTP/1.1 502 Bad Gateway

#retries: 1
Wait time(ms): 100
HTTP Status: 502

Connection error: Expecting status 101 (Switching Protocol), got 502 status connecting to wss://ixws.luastoned.com, HTTP Status line: HTTP/1.1 502 Bad Gateway

#retries: 2
Wait time(ms): 200
HTTP Status: 502

Connection error: Expecting status 101 (Switching Protocol), got 502 status connecting to wss://ixws.luastoned.com, HTTP Status line: HTTP/1.1 502 Bad Gateway

```

I'm getting errors too talking to your service, and this is on mac, using the SecureTransport, so maybe it isn't mbedtls related.

**Comment by bsergean** [comment]
server

```
node$ node issue_323_node_server.js
received 5
received 22
```

client

```
issue_323$ ./node_modules/.bin/wscat -c ws://localhost:8080 
Connected (press CTRL+C to quit)
> youpi
> you yoyou asdcasd casd
> c
```

Works just fine with wscat. I think it has to do with the zlib extension. If I turn it off things work well.

**Comment by bsergean** [comment]
```
node$ cat issue_323_node_server.js 
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8080, perMessageDeflate: false });

wss.on('connection', (ws) => {
  ws.on('message', (data) => {
    console.log('received', data.length);
  });
});
```

To connect with zlib extension off, I pass the -x option

```
ws connect -x ws://localhost:8080 
```

Call this method on your websocket client object to workaround the problem

*disablePerMessageDeflate();*

**Comment by luastoned** [comment]
Hello,

I started the server with pm2 so it will restart on it's own now.

I haven't compiled the ws cli tool on Windows yet, CMake and it's requirements about ZLIB are kinda odd.

The snippet in the OP is everything I do though. So `disablePerMessageDeflate();` gets called.

The problem seems to only appear with IXWS on Windows -> wss proxy (nginx) -> node/python ws server

**Comment by bsergean** [comment]
FYI I'm not sure of when I'll have time to investigate this, so don't hold your breath until I find the problem ...

**Comment by bsergean** [comment]
One thing you can try too is to try an older version, maybe this is a recent regression.

10.3.1 is a version that has been used in production for a lot.

**Comment by luastoned** [comment]
I tested 10.2.5 and even back then the error exists.

**Comment by ahausladen** [comment]
I think a better solution would be to wait for the socket to be writable again instead of waiting 25 milliseconds.

```
            if (ret < 0 && Socket::isWaitNeeded())
            {
                PollResultType pollResult = _socket->isReadyToWrite(-1); // no timeout
                if (pollResult != PollResultType::ReadyForWrite)
                {
                    closeSocket();
                    setReadyState(ReadyState::CLOSED);
                    return false;
                }
            }
```

**Comment by ahausladen** [comment]
After some debugging I found what causes the problem: The background thread doesn't start sending the tx-buffer because it never gets notified to do so. But this only happens under Windows because there is no implementation for "SelectInterrupt" (for other platforms there is the SelectInterruptPipe implementation).

```
    bool SelectInterrupt::notify(uint64_t /*value*/)
    {
        return true;
    }
```
The missing Windows implementation was already discussed in #131.

For Windows the WSAEventSelect, WSAWaitForMultipleEvents and WSAEnumNetworkEvents APIs could be used to combine a socket with a simple "event" that can wake up the thread and then query a SelectInterrupt implemenation that holds the SendRequest and CloseRequest.

**Comment by luastoned** [comment]
Wow alright, thanks for taking the time to properly debug and fix this.

**Comment by bsergean** [comment]
ps: we should avoid making this a blocking send, as on some platform (mobile) blocking the main thread can trigger an application to be killed. (+ it's bad behavior, it freeze the UI etc...).

Thanks for debugging this @ahausladen !

**Comment by luastoned** [comment]
Well, I've got some not-so-great news. The issue still persists for larger messages.
Looking at my previous answer, the loop still breaks and causes issues for the next chunk.
